.github/workflows/django_tests.yml
Dockerfile
corpus/corpus/settings.py
corpus/start_livecycle.sh
env.example

Adding a Dockerfile and settings changes for [Livecycle](https://www.livecycle.io/) deployment. Just checking how the service works. Seems pretty legit so far.
Might have a dependency on:
- [Livecycle](https://www.livecycle.io/)
---

Add Dockerfile and settings changes for livecycle deployment

---

corpus/corpus/settings.py
corpus/start_livecycle.sh

Fixing Lifecycle deployment to have Debug set to `TRUE`
---

Fix lifecycle deployment

---

corpus/corpus/settings.py

Small error in CSRF hosts configuration prevents Livecycle builds from completing. Fixed here.
---

Fix CSRF Hosts in Livecycle container

---

corpus/requirements.txt

Previously, we had the normal Postgres plugin for our project, which was built from scratch on every download. This replaces it with the prebuilt binary, so we do not have to keep building on every time environments are created.
---
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are …

Replace psycopg2 with the binary version

---

corpus/corpus/settings.py

Update all `os.environ` dict calls to `os.getenv` calls. This is a safer method of calling environment variables because `getenv` returns `None` if the variable doesn't exist.
Fixes #31 
N/A
---

Update all os.environ dict calls to os.getenv calls

---

corpus/accounts/views.py
corpus/embedathon/views.py
corpus/templates/accounts/login.html
corpus/templates/base.html
corpus/templates/components/general_dropdown.html
corpus/templates/components/navbar_dropdown.html
corpus/templates/embedathon/index.html

Added checks for maximum number of team members

---

corpus/embedathon/urls.py
corpus/embedathon/views.py
corpus/templates/base.html
corpus/templates/components/dark_mode_toggle.html
corpus/templates/components/general_dropdown.html
corpus/templates/embedathon/home.html
corpus/templates/embedathon/index.html
corpus/templates/embedathon/register.html

Add home page for embedathon

---

corpus/templates/embedathon/home.html

Added info about embedathon

---

corpus/corpus/decorators.py
corpus/embedathon/urls.py
corpus/embedathon/views.py
corpus/templates/embedathon/admin.html
corpus/templates/embedathon/base.html
corpus/templates/embedathon/home.html
corpus/templates/embedathon/index.html
corpus/templates/embedathon/register.html
corpus/templates/embedathon/team_management.html
corpus/templates/embedathon/team_page.html
corpus/templates/embedathon/user_management.html

Embedathon admin page

---

corpus/templates/accounts/signup.html
corpus/templates/embedathon/home.html

Some content changes

---

corpus/templates/embedathon/home.html
corpus/templates/embedathon/team_page.html
corpus/templates/embedathon/user_management.html

Fix timing

---

corpus/embedathon/forms.py
corpus/templates/embedathon/register.html

Added roll number verification for NITK students

---

corpus/corpus/settings.py
docker-compose.yml
env.example
prod-docker-compose.yml

Sets up functionality and configurations to send mails for Corpus.
---

Setup mailing

---

corpus/corpus/utils.py
corpus/embedathon/forms.py
corpus/embedathon/views.py
corpus/templates/emails/base.html
corpus/templates/emails/embedathon/announcement.html
corpus/templates/embedathon/announcements_management.html

Introduces a generic util function for sending emails, and sends Embedathon announcements as emails.
---

Send announcements as email in Embedathon

---

corpus/impulse/views.py

Impulse Module
Missing `module_enabled` decorator for impulse home view.
- [] New feature (non-breaking change which adds functionality)
---

Impulse 2024

---

corpus/templates/embedathon/home.html

Add session link

---

corpus/embedathon/views.py
corpus/templates/embedathon/home.html
corpus/templates/embedathon/team_management.html
corpus/templates/embedathon/user_management.html

Embedathon add stats and resources

---

corpus/impulse/urls.py
corpus/impulse/views.py
corpus/templates/emails/embedathon/announcement.html
corpus/templates/emails/impulse/announcement.html
corpus/templates/embedathon/index.html
corpus/templates/impulse/admin/announcements.html
corpus/templates/impulse/index.html

Fix line breaks in announcement email content

---

corpus/templates/embedathon/home.html

Add workshops

---

corpus/impulse/urls.py
corpus/impulse/views.py
corpus/templates/impulse/admin/announcements.html
corpus/templates/impulse/admin/teams.html
corpus/templates/impulse/admin/users.html

Add groupify functionality and team download feature

---

corpus/templates/embedathon/home.html

Add workshop 1 resources

---

corpus/Dockerfile

Production environments were not doing `npm install` to install dependencies. Fixed that now.
---

Fix production Dockerfile

---

corpus/templates/electrika/home.html

Electrika 2024

---

corpus/templates/components/general_dropdown.html
corpus/templates/skyward_expedition/home.html

Fix skyward expedition on mobile

---

corpus/templates/skyward_expedition/home.html

Fix dark mode

---

corpus/templates/skyward_expedition/home.html

Edit contact email

---

corpus/templates/skyward_expedition/home.html

Skyward expedition faqs

---

corpus/corpus/settings.py
nginx/default.conf
prod-docker-compose.yml

Add media configurations to allow media uploads on Corpus
None
Test it on production xD
---

Add media upload capability

---

corpus/templates/robotrix/home.html
corpus/templates/robotrix/index.html

Update links and remove extra whitespace in home.html and index.html

---

corpus/templates/skyward_expedition/admin/teams_dashboard.html

Fix teams page

---

corpus/skyward_expedition/admin.py

Add models to django admin

---

corpus/dev-Dockerfile

Add the libmagic dependency to the dev dockerfile as well.
---

Add magic dependencies to dev dockerfile

---

corpus/corpus/settings.py
corpus/virtual_expo/admin_views.py
corpus/virtual_expo/member_views.py
corpus/virtual_expo/models.py

This adds checks for SIG uniques and other checks.
None
---

[Virtual Expo] Add SIG uniqueness and others checks

---

corpus/virtual_expo/admin_views.py
corpus/virtual_expo/views.py

Added distinct checks for filtering

---

corpus/virtual_expo/forms.py

Fix the queries on the Virtual Expo model, to fix failing pipelines as well.
Fixes #144 
None
Tested on a new local instance.
---

Fix virtual expo forms for pipelines

---

corpus/accounts/urls.py

Fix the html rendering of the reset password emails
---

Fix reset email rendering

---

corpus/accounts/urls.py

Fix the path to the html text email
Fixes #148 

Fix reset email

---

corpus/accounts/views.py

Fix 500 Error on login page: https://corpus-ieee.sentry.io/issues/5057429343/?project=4506774434414592
---

Fix list index error

---

corpus/templates/virtual_expo/report.html

Minor virtual expo fix

---

corpus/templates/virtual_expo/members/dashboard.html

User expo dashboard fix

---

corpus/templates/embedathon/home.html

Updated the dates for the Embedathon application.
- [x ] This change requires a documentation update
---

Embedathon Dates changed

---

corpus/templates/robotrix/home.html

Updates made for the Robotrix home page regarding the description, eligibility, dates, prizes and schedule.
---

Robotrix2024

---

corpus/templates/diodexcelerate/home.html

Add links and organizing logos

---

corpus/requirements.txt

This PR bumps Django version to `5.1.2`
Fixes #96 
```
Django==5.1.3
asgiref==3.8.1
```
- [ x] Test `accounts`
- Manually checked some URLs to see if they are fine.
---

Bumped Django to version 5.1.3

---

corpus/templates/robotrix/home.html

The description under the prizes changed.
---

Robotrix Home Page Prizes Text changed

---

corpus/templates/pages/sig.html

About Us details of each Sig Centre Aligned.
Fixes #108 
- [x ] Bug fix (non-breaking change which fixes an issue)
---

Alignment issue in Sigs pages

---

corpus/templates/impulse/home.html

Required changes regarding the price and the details of the last FAQ of Impulse modified.
---

Impulse Price and last FAQ details changed

---

corpus/templates/components/navbar_list.html

Add a membership item in the navbar list which contains 3 links-
1. Registration Form
2. Whatsapp Group
3. PPT link

Add membership drive links to navbar

---

corpus/templates/404.html

Responsive Issues for the 404 page
---

responsive issues 404 page

---

corpus/blog/views.py

Right Now when hitting the route /blogs/id if the id does not exist, we get a 500 (internal server error) with this change we will now display the 404 page.
---

Return 404 in case no blog existed

---

corpus/templates/accounts/edit_profile.html

Added error handling for missing profile_pic.url in the fronted check.
Fixes #192 
---

Profile picture Error

---

corpus/templates/virtual_expo/report.html
corpus/templates/virtual_expo/reports_by_year.html

This is the UI revamp of virtual expo page.
**Reports Preview:**
**Report Itself:**
---

Redesign of virtual expo page

---

corpus/accounts/admin.py

Allow admin users to change and view profile pictures for users in the admin dashboard
---

Allow admins to change profile pictures

---

corpus/templates/virtual_expo/reports_by_year.html

Ensuring the image height is fixed
---

stretch images to fit Box. fix height to 64

---

corpus/corpus/settings.py

Allow editor functionality to copy-paste images from local file system to the ckeditor textbox
---

Allow functionality to paste images from local filesystem

---

corpus/corpus/settings.py

Reverts a change which might have broken a few functionalities
---

Patch for MEDIA_ROOT

---

corpus/templates/virtual_expo/report.html

This adds project abstract just before displaying the content
---

Abstract section before content

---

corpus/corpus/decorators.py
corpus/virtual_expo/views.py

Do not allow public users to view envision reports until allowed to do so through module configuration.
---

Do not allow public users to view current envision reports

---

corpus/templates/components/navbar_list.html

Avoid cluttering of the navbar by removing membership drive
---

Remove membership drive from navbar

---

corpus/accounts/admin.py
corpus/pages/views.py
corpus/templates/pages/core_box.html
corpus/templates/pages/faculty_box.html
corpus/templates/pages/member_box.html
corpus/templates/pages/team.html

Update HTML in TeamPage
